### ISSUE TITLE
NOT WORKING FOR SAFARI

### ISSUE THREAD

**Issue by LTFENG** [cyan33/image-screenshot#2]
Hi, dear @cyan33 

Thanks for your library, is that any solution to make the filter work in safari ?

Thank you once again.

**Comment by cyan33** [comment]
Hey @LTFENG, I think this has already been fixed thru https://github.com/cyan33/image-screenshot/pull/1. Will do a release today.

**Comment by cyan33** [comment]
https://github.com/cyan33/image-screenshot/commit/26361a021b8b5c80293f586b336dcef8dcce57aa
